apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapp.fullname" . }}
  labels:
    {{- include "fastapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "fastapp.name" . }}